<?php

namespace ContainerCcgUVol;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatePriceTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Application\CalculatePriceType' shared autowired service.
     *
     * @return \App\Form\Application\CalculatePriceType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Application/CalculatePriceType.php';

        return $container->privates['App\\Form\\Application\\CalculatePriceType'] = new \App\Form\Application\CalculatePriceType();
    }
}
