<?php

namespace ContainerV5UxfpJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ye6QAgnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ye6QAgn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ye6QAgn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CalculatePriceServiceInterface' => ['privates', 'App\\Service\\CalculatePriceService', 'getCalculatePriceServiceService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'CalculatePriceServiceInterface' => '?',
            'doctrine' => '?',
            'validator' => '?',
        ]);
    }
}
