<?php

namespace ContainerKO6v3RC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RSQlYGbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rSQlYGb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rSQlYGb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Api\\EndpointCalculatePriceController::CalculatePrice' => ['privates', '.service_locator.z.l5ZCv', 'get_ServiceLocator_Z_L5ZCvService', true],
            'App\\Controller\\Api\\EndpointPurchaseController::productPayment' => ['privates', '.service_locator.zlMnlNy', 'get_ServiceLocator_ZlMnlNyService', true],
            'App\\Controller\\Application\\ApplicationController::CalculatePrice' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\Application\\ApplicationController::Purchase' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\Api\\EndpointCalculatePriceController:CalculatePrice' => ['privates', '.service_locator.z.l5ZCv', 'get_ServiceLocator_Z_L5ZCvService', true],
            'App\\Controller\\Api\\EndpointPurchaseController:productPayment' => ['privates', '.service_locator.zlMnlNy', 'get_ServiceLocator_ZlMnlNyService', true],
            'App\\Controller\\Application\\ApplicationController:CalculatePrice' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\Application\\ApplicationController:Purchase' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\Api\\EndpointCalculatePriceController::CalculatePrice' => '?',
            'App\\Controller\\Api\\EndpointPurchaseController::productPayment' => '?',
            'App\\Controller\\Application\\ApplicationController::CalculatePrice' => '?',
            'App\\Controller\\Application\\ApplicationController::Purchase' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Api\\EndpointCalculatePriceController:CalculatePrice' => '?',
            'App\\Controller\\Api\\EndpointPurchaseController:productPayment' => '?',
            'App\\Controller\\Application\\ApplicationController:CalculatePrice' => '?',
            'App\\Controller\\Application\\ApplicationController:Purchase' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
