<?php

namespace ContainerKO6v3RC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurchaseServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PurchaseService' shared autowired service.
     *
     * @return \App\Service\PurchaseService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PurchaseServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/PurchaseService.php';

        return $container->privates['App\\Service\\PurchaseService'] = new \App\Service\PurchaseService();
    }
}
