<?php

namespace Container1NV1L7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3pzZ9u0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3pzZ9u0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3pzZ9u0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'CalculatePriceServiceInterface' => ['privates', 'App\\Service\\CalculatePriceService', 'getCalculatePriceServiceService', true],
            'couponsRepository' => ['privates', 'App\\Repository\\CouponsRepository', 'getCouponsRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'productsRepository' => ['privates', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', true],
            'taxesRepository' => ['privates', 'App\\Repository\\TaxesRepository', 'getTaxesRepositoryService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'CalculatePriceServiceInterface' => '?',
            'couponsRepository' => 'App\\Repository\\CouponsRepository',
            'doctrine' => '?',
            'productsRepository' => 'App\\Repository\\ProductsRepository',
            'taxesRepository' => 'App\\Repository\\TaxesRepository',
            'validator' => '?',
        ]);
    }
}
