<?php

namespace ContainerVOM0jH7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ttwf9yyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ttwf9yy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ttwf9yy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Application\\ApplicationController::CalculatePrice' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\Application\\ApplicationController::Purchase' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController::CalculatePriceWithACoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController::CalculatePriceWithoutCoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController::PurchaseWithACoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController::PurchaseWithoutCoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\Application\\ApplicationController:CalculatePrice' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\Application\\ApplicationController:Purchase' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController:CalculatePriceWithACoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController:CalculatePriceWithoutCoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController:PurchaseWithACoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController:PurchaseWithoutCoupon' => ['privates', '.service_locator.6B_ZjHa', 'get_ServiceLocator_6BZjHaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\Application\\ApplicationController::CalculatePrice' => '?',
            'App\\Controller\\Application\\ApplicationController::Purchase' => '?',
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController::CalculatePriceWithACoupon' => '?',
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController::CalculatePriceWithoutCoupon' => '?',
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController::PurchaseWithACoupon' => '?',
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController::PurchaseWithoutCoupon' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Application\\ApplicationController:CalculatePrice' => '?',
            'App\\Controller\\Application\\ApplicationController:Purchase' => '?',
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController:CalculatePriceWithACoupon' => '?',
            'App\\Controller\\EndpointCalculatePrice\\EndpointCalculatePriceController:CalculatePriceWithoutCoupon' => '?',
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController:PurchaseWithACoupon' => '?',
            'App\\Controller\\EndpointPurchase\\EndpointPurchaseController:PurchaseWithoutCoupon' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
