<?php

namespace ContainerXN1QCcy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hi.gBQz.Symfony\Component\HttpFoundation\JsonResponse' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hi.gBQz": it references class "Symfony\\Component\\HttpFoundation\\JsonResponse" but no such service exists.');
    }
}
