<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnVBbtE\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnVBbtE/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCnVBbtE.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCnVBbtE\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCnVBbtE\App_KernelTestDebugContainer([
    'container.build_hash' => 'CnVBbtE',
    'container.build_id' => 'd5d59521',
    'container.build_time' => 1699269696,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnVBbtE');
