<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWTdZxsQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWTdZxsQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWTdZxsQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWTdZxsQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWTdZxsQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'WTdZxsQ',
    'container.build_id' => '0f38fda2',
    'container.build_time' => 1707145161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWTdZxsQ');
