<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCcgUVol\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcgUVol/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCcgUVol.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCcgUVol\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCcgUVol\App_KernelDevDebugContainer([
    'container.build_hash' => 'CcgUVol',
    'container.build_id' => '3f41698a',
    'container.build_time' => 1707922419,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcgUVol');
